import EventEmitter from 'core/EventEmitter';
import Logger from 'core/Logger';
import Renderer from 'core/Renderer';
import Reactors from 'core/Reactors';
import Stage from 'core/Stage';
import Player from 'audio/Player';
import SpectrumAnalyzer from 'audio/SpectrumAnalyzer';
import VideoRenderer from 'video/VideoRenderer';
import { SAMPLE_RATE } from './constants';

export const api = window.__ASTROFOX__;
export const env = api.getEnvironment();
export const audioContext = new window.AudioContext({ sampleRate: SAMPLE_RATE});
export const logger = new Logger('astrofox');
export const events = new EventEmitter();
export const stage = new Stage();
export const player = new Player(audioContext);
export const analyzer = new SpectrumAnalyzer(audioContext);
export const reactors = new Reactors();
export const renderer = new Renderer();
export const videoRenderer = new VideoRenderer(renderer);
export const library = new Map();
