import {
	ChevronsLeft as AngleDoubleLeft,
	ChevronsRight as AngleDoubleRight,
	MoveHorizontal as ArrowsHorizontal,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronUp,
	Box as Cube,
	Repeat as Cycle,
	FileText as DocumentLandscape,
	Ellipsis as DotsHorizontal,
	Expand,
	Eye,
	Zap as Flash,
	FolderOpen,
	Lightbulb as LightUp,
	Link,
	Minus,
	Pause,
	Image as Picture,
	Play as PlayBase,
	Plus,
	Sun,
	AudioLines as SoundBars,
	Waves as SoundWaves,
	Square,
	Square as StopBase,
	X as Times,
	Trash2 as TrashEmpty,
	Volume2 as Volume,
	Volume1 as Volume2,
	Volume as Volume3,
	VolumeX as Volume4,
	TriangleAlert as Warning,
} from "lucide-react";

export {
	AngleDoubleLeft,
	AngleDoubleRight,
	ArrowsHorizontal,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronUp,
	Cube,
	Cycle,
	DocumentLandscape,
	DotsHorizontal,
	Expand,
	Eye,
	FolderOpen,
	Flash,
	LightUp,
	Link,
	Minus,
	Pause,
	Picture,
	Plus,
	Sun,
	SoundBars,
	SoundWaves,
	Square,
	Times,
	TrashEmpty,
	Volume,
	Volume2,
	Volume3,
	Volume4,
	Warning,
};

export function Play(props) {
	return <PlayBase strokeWidth={2.4} {...props} />;
}

export function Stop(props) {
	return <StopBase strokeWidth={2.4} {...props} />;
}
