import {
	CaretDoubleLeft as AngleDoubleLeft,
	CaretDoubleRight as AngleDoubleRight,
	ArrowsHorizontal,
	CaretDown as ChevronDown,
	CaretLeft as ChevronLeft,
	CaretRight as ChevronRight,
	CaretUp as ChevronUp,
	Cube,
	ArrowsClockwise as Cycle,
	File as DocumentLandscape,
	DotsThree as DotsHorizontal,
	ArrowsOut as Expand,
	Eye,
	Lightning as Flash,
	FolderOpen,
	Lightbulb as LightUp,
	Link,
	Minus,
	Pause,
	ImageSquare as Picture,
	Play as PlayIcon,
	Plus,
	Waveform as SoundBars,
	WaveSine as SoundWaves,
	Square,
	Stop as StopIcon,
	X as Times,
	Trash as TrashEmpty,
	SpeakerHigh as Volume,
	SpeakerLow as Volume2,
	SpeakerNone as Volume3,
	SpeakerSimpleX as Volume4,
	Warning,
} from "@phosphor-icons/react";

export {
	AngleDoubleLeft,
	AngleDoubleRight,
	ArrowsHorizontal,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronUp,
	Cube,
	Cycle,
	DocumentLandscape,
	DotsHorizontal,
	Expand,
	Eye,
	FolderOpen,
	Flash,
	LightUp,
	Link,
	Minus,
	Pause,
	Picture,
	Plus,
	SoundBars,
	SoundWaves,
	Square,
	Times,
	TrashEmpty,
	Volume,
	Volume2,
	Volume3,
	Volume4,
	Warning,
};

export function Play(props) {
	return <PlayIcon weight="fill" {...props} />;
}

export function Stop(props) {
	return <StopIcon weight="fill" {...props} />;
}
