module.exports = {
    "Normal": 1,
    "Dissolve": 2,
    "Darken": 3,
    "Multiply": 4,
    "Color Burn": 5,
    "Linear Burn": 6,
    "Darker Color": 7,
    "Lighten": 8,
    "Screen": 9,
    "Color Dodge": 10,
    "Linear Dodge": 11,
    "Lighter Color": 12,
    "Overlay": 13,
    "Soft Light": 14,
    "Hard Light": 15,
    "Vivid Light": 16,
    "Linear Light": 17,
    "Pin Light": 18,
    "Hard Mix": 19,
    "Difference": 20,
    "Exclusion": 21,
    "Subtract": 22,
    "Divide": 23,
    "Add": 24
};