module.exports = {
    Normal: 1,
    Dissolve: 2,
    Darken: 3,
    Multiply: 4,
    ColorBurn: 5,
    LinearBurn: 6,
    DarkerColor: 7,
    Lighten: 8,
    Screen: 9,
    ColorDodge: 10,
    LinearDodge: 11,
    LighterColor: 12,
    Overlay: 13,
    SoftLight: 14,
    HardLight: 15,
    VividLight: 16,
    LinearLight: 17,
    PinLight: 18,
    HardMix: 19,
    Difference: 20,
    Exclusion: 21,
    Subtract: 22,
    Divide: 23,
    Add: 24
};