/*
module.exports = {
    "Normal": 1,
    "Dissolve": 2,
    "Darken": 3,
    "Multiply": 4,
    "Color Burn": 5,
    "Linear Burn": 6,
    "Darker Color": 7,
    "Lighten": 8,
    "Screen": 9,
    "Color Dodge": 10,
    "Linear Dodge": 11,
    "Lighter Color": 12,
    "Overlay": 13,
    "Soft Light": 14,
    "Hard Light": 15,
    "Vivid Light": 16,
    "Linear Light": 17,
    "Pin Light": 18,
    "Hard Mix": 19,
    "Difference": 20,
    "Exclusion": 21,
    "Subtract": 22,
    "Divide": 23,
    "Add": 24
};
*/
module.exports = {
    "Add": 1,
    "Average": 2,
    "Color Burn": 3,
    "Color Dodge": 4,
    "Darken": 5,
    "Difference": 6,
    "Exclusion": 7,
    "Glow": 8,
    "Hard Light": 9,
    "Hard Mix": 10,
    "Lighten": 11,
    "Linear Burn": 12,
    "Linear Dodge": 13,
    "Linear Light": 14,
    "Multiply": 15,
    "Negation": 16,
    "Normal": 17,
    "Overlay": 18,
    "Phoenix": 19,
    "Pin Light": 20,
    "Reflect": 21,
    "Screen": 22,
    "Soft Light": 23,
    "Subtract": 24,
    "Vivid Light": 25
};